#!/usr/bin/env bash
#
# Usage: dockerize envs [ENV_1 ENV_2]
#
# Summary: Docker-friendly envs
#
# Help: Converts all environment variables to docker-friendly ones
#
#   export TCP_PORT=9292
#   export REDIS_URI="redis://172.0.0.13:6379"
#
#   dockerize envs TCP_PORT UDP_PORT REDIS_URI
#   -e TCP_PORT=9292 -e REDIS_URI="redis://172.0.0.13:6379"
#
# As env var UDP_PORT does not have a value, it will be omitted

if [ -z "$1" ]
then
  echo "Expecting at least one environment variable"
  exit 1
fi

envs="$@"
docker_envs=()

for _env in ${envs[@]}
do
  if [ -n "${!_env}" ]
  then
    docker_envs+=("-e $_env=${!_env}")
  fi
done

__command="echo \"\${docker_envs[@]}\""

$__exec $__command
