#!/usr/bin/env bash
#
# Usage: dockerize github user/repository[:branch] [docker_image]
#
# Summary: Build images from github repositories
#
# Help: Repositories that have a Dockerfile in them will be turned into an image
#
#   dockerize github cambridge-healthcare/hi_sinatra-docker hi_sinatra
#
# Dockerize adds a few conventions on top of Docker's default build behaviour:
#
# * github credentials management (caching or storing)
# * always clones the github repository
# * always builds from the local directory (think ADD . /app_name)
# * enables you to leverage the ADD command to its full potential

if [ -z "$(type -p git)" ]
then
  echo "Cannot find git. Is git installed and available in the PATH?"
  exit 1
fi

git_version="$(git --version | awk '{ print $3 }')"
git_version_num="${git_version//./}"

if [ "$git_version_num" -lt 1790 ]
then
  echo "git v1.7.9.0 or newer required"
  exit 1
fi

# Setting up github credentials caching
# There are 2 requirements for this:
#   1. git >= 1.7.9
#   2. git pull via https
#
# More info:
#   * https://www.kernel.org/pub/software/scm/git/docs/git-credential-store.html
#   * https://help.github.com/articles/set-up-git
#
if [[ ! -e "$HOME/.git-credentials" && ! -e "$HOME/.no_prompting_for_credentials" ]]
then
  echo "Should git manage github credentials?"
  github_credentials_options=(
    "Cache credentials for 10 minutes"
    "Store credentials in plaintext"
    "No, don't manage credentials"
  )
  select answer in "${github_credentials_options[@]}"
  do
    touch "$HOME/.no_prompting_for_credentials"

    case $answer in
    "${github_credentials_options[0]}" )
      git config --global credential.helper cache
      break
      ;;
    "${github_credentials_options[1]}" )
      git config --global credential.helper store
      echo "Storing github credentials in plaintext"
      read -p "Github username: " github_username
      read -p "Github password: " github_password
      echo "https://$github_username:$github_password@github.com" > $HOME/.git-credentials
      break
      ;;
    "${github_credentials_options[2]}" )
      break
      ;;
    esac
  done
fi

if [ -z "$1" ]
then
  echo "Must specify a github user/repository"
  exit 1
fi

github_repo_name_and_branch=(${1/:/ })
github_repo="${github_repo_name_and_branch[0]}"
github_repo_branch="${github_repo_name_and_branch[1]:-master}"
shift

docker_image="${1:-${github_repo/*\//}}"
cloned_repository="$DOCKER_GITHUB_REPOS/$docker_image"

if [ ! -e "$cloned_repository" ]
then
  $__exec "git clone https://github.com/${github_repo}.git $cloned_repository"
  $__exec "cd $cloned_repository"
else
  $__exec "cd $cloned_repository && git fetch"
fi

$__exec "git checkout -f origin/$github_repo_branch"
if [ $? -ne 0 ]
then
  echo "Branch origin/$github_repo_branch does not exist"
  exit 1
fi

commit_sha="$($__exec git rev-parse --short HEAD)"
docker_image_tag="${github_repo_branch}.${commit_sha}"

if [[ $PWD == $cloned_repository && ! -e Dockerfile ]]
then
  echo "This repository does not contain a Dockerfile, cannot build Docker image"
  exit 1
fi

if [[ -z $(dockerize images | grep $docker_image | grep " base ") ]]
then
  $__exec "docker build -no-cache -rm -t $docker_image:base ."
fi

if [[ -n $(dockerize images | grep $docker_image | grep $docker_image_tag) ]]
then
  echo "Container $docker_image:$docker_image_tag already built"
else
  $__exec "sed 's|FROM .*|FROM $docker_image:base|g' Dockerfile > Dockerfile.new"
  $__exec "mv Dockerfile Dockerfile.bak && mv Dockerfile.new Dockerfile"
  $__exec "docker build -no-cache -rm -t $docker_image:$docker_image_tag ."
fi
