#!/usr/bin/env bash
#
# Usage: dockerize list [filter]
#
# Summary: List all containers, supports filtering
#
# Help: List all containers (running or not), supports filtering
#
#   dockerize list
#   dockerize list Exit 127
#   dockerize list "ruby-build|ubuntu"
#
# Since all arguments are passed to awk regexp, filter combinations are also possible:
#
#   dockerize list "ubuntu/ && ! /Exit 0"

filter="$@"

__command="docker ps -a | awk '/$filter/'"

$__exec $__command
