#!/usr/bin/env bash
set -e

export __exec="eval"

# Turn on debug mode, all commands are just dry runs, no action will be taken
case "$1" in
-d | --d* )
  echo "Running in debug mode, no commands will be executed"
  set -x
  export __exec="echo"
  shift
esac

if [ -z "$(type -p docker)" ]
then
  echo "Cannot find docker. Is docker installed and available in the PATH?"
  exit 1
fi

DOCKER_CIDS_DIR="${DOCKER_CIDS_DIR:-/var/run/docker_cids}"
if [ ! -d "$DOCKER_CIDS_DIR" ]
then
  echo "Docker directory for storing container IDs does not exist, creating it now..."
  $__exec "sudo mkdir $DOCKER_CIDS_DIR"
  echo "Done!"
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _DOCKERIZE_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

command="$1"
case "$command" in
"" | -h | --h* )

  $__exec "dockerize-help"

  ;;
-v | --v* )

  $__exec "echo 'dockerize v0.1.0'"

  ;;
* )

  command_path="$(command -v "dockerize-$command" || true)"
  shift

  if [ ! -x "$command_path" ]
  then
    command_path="$(command -v docker) $command"
  fi

  $__exec "$command_path $@"

  ;;
esac
